import { NextResponse } from 'next/server';
import getDb from '@/app/utils/db';
import { RowDataPacket } from 'mysql2';

interface BillDownloadData extends RowDataPacket {
  CM_Purchase_Summary_ID: string;
  CM_Supplier_ID: string;
  CM_Company_ID: string;
  CM_Bill_Number: string;
  CM_Tax_Type: 'GST' | 'CGST/SGST';
  CM_Tax_Percentage: number;
  CM_Tax_Amount: number;
  CM_Payment_Terms: string;
  CM_Grand_Total: number;
  CM_Advance_Payment: number;
  CM_Balance_Payment: number;
  CM_Delivery_Location: string;
  CM_Delivery_Date: Date;
  CM_Payment_Status: 'Paid' | 'Partially Paid' | 'Unpaid';
  CM_Round_off: number;
  CM_Created_By: string;
  CM_Created_At: Date;
  CM_Uploaded_By: string;
  CM_Uploaded_At: Date;
}

export async function GET(
  request: Request,
  props: { params: Promise<{ billId: string }> }
) {
  try {
    const params = await props.params;
    const billId = params.billId;
    const { searchParams } = new URL(request.url);
    const format = searchParams.get('format') || 'txt';

    const db = await getDb();

    const [bills] = await db.query<BillDownloadData[]>(`
      SELECT * FROM ccms_purchase_summary 
      WHERE CM_Purchase_Summary_ID = ? OR CM_Bill_Number = ?
    `, [billId, billId]);

    if (bills.length === 0) {
      return new Response('Bill not found', { status: 404 });
    }

    const bill = bills[0];

    // Format values
    const grandTotal = parseFloat(bill.CM_Grand_Total?.toString() || '0');
    const advancePayment = parseFloat(bill.CM_Advance_Payment?.toString() || '0');
    const balancePayment = parseFloat(bill.CM_Balance_Payment?.toString() || '0');
    const taxAmount = parseFloat(bill.CM_Tax_Amount?.toString() || '0');
    const taxPercentage = parseFloat(bill.CM_Tax_Percentage?.toString() || '0');
    const roundOff = parseFloat(bill.CM_Round_off?.toString() || '0');

    if (format === 'pdf') {
      // For PDF, return HTML that can be converted to PDF on the client side
      const html = generatePDFHTML(bill, {
        grandTotal,
        advancePayment,
        balancePayment,
        taxAmount,
        taxPercentage,
        roundOff
      });

      const res = new Response(html, {
        headers: {
          'Content-Type': 'text/html',
          'X-PDF-Data': 'true' // Custom header to identify PDF HTML
        },
      });
      res.headers.set('Cache-Control', 'no-store');
      return res;
    }

    if (format === 'csv') {
      const csvContent = `
Bill ID,Bill Number,Supplier ID,Company ID,Tax Type,Tax Percentage,Tax Amount,Grand Total,Advance Payment,Balance Payment,Payment Status,Delivery Location,Delivery Date,Payment Terms,Round Off,Created By,Created At
"${bill.CM_Purchase_Summary_ID}","${bill.CM_Bill_Number}","${bill.CM_Supplier_ID || ''}","${bill.CM_Company_ID || ''}","${bill.CM_Tax_Type}","${taxPercentage}","${taxAmount}","${grandTotal}","${advancePayment}","${balancePayment}","${bill.CM_Payment_Status}","${bill.CM_Delivery_Location || ''}","${bill.CM_Delivery_Date ? new Date(bill.CM_Delivery_Date).toLocaleDateString('en-IN') : ''}","${bill.CM_Payment_Terms || ''}","${roundOff}","${bill.CM_Created_By || ''}","${new Date(bill.CM_Created_At).toLocaleString('en-IN')}"
      `.trim();

      const res = new Response(csvContent, {
        headers: {
          'Content-Type': 'text/csv',
          'Content-Disposition': `attachment; filename="bill_${bill.CM_Bill_Number}.csv"`
        },
      });
      res.headers.set('Cache-Control', 'no-store');
      return res;
    }

    // Default text format
    const content = `
PURCHASE BILL SUMMARY
=====================

Bill Information:
-----------------
Bill ID: ${bill.CM_Purchase_Summary_ID}
Bill Number: ${bill.CM_Bill_Number}
Supplier ID: ${bill.CM_Supplier_ID || 'N/A'}
Company ID: ${bill.CM_Company_ID || 'N/A'}
Created By: ${bill.CM_Created_By || 'N/A'}

Financial Details:
------------------
Tax Type: ${bill.CM_Tax_Type}
Tax Percentage: ${taxPercentage.toFixed(2)}%
Tax Amount: ₹${taxAmount.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
Round Off: ₹${roundOff.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
Grand Total: ₹${grandTotal.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
Amount Paid: ₹${advancePayment.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
Balance Amount: ₹${balancePayment.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
Payment Status: ${bill.CM_Payment_Status}

Delivery Information:
---------------------
Delivery Location: ${bill.CM_Delivery_Location || 'N/A'}
Delivery Date: ${bill.CM_Delivery_Date ? new Date(bill.CM_Delivery_Date).toLocaleDateString('en-IN') : 'N/A'}
Payment Terms: ${bill.CM_Payment_Terms || 'N/A'}

Timestamps:
-----------
Created: ${new Date(bill.CM_Created_At).toLocaleString('en-IN')}
Downloaded: ${new Date().toLocaleString('en-IN')}

Generated by Purchase Management System
    `.trim();

    const res = new Response(content, {
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename="bill_${bill.CM_Bill_Number}.txt"`
      },
    });
    res.headers.set('Cache-Control', 'no-store');
    return res;
  } catch (error) {
    console.error('Error downloading bill:', error);
    const res = new Response('Error downloading bill', { status: 500 });
    res.headers.set('Cache-Control', 'no-store');
    return res;
  }
}

function generatePDFHTML(bill: BillDownloadData, amounts: any) {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Bill ${bill.CM_Bill_Number}</title>
      <style>
        body { 
          font-family: 'Arial', sans-serif; 
          margin: 0; 
          padding: 20px; 
          background: white;
          color: #333;
          line-height: 1.6;
        }
        .container { 
          max-width: 800px; 
          margin: 0 auto;
        }
        .header { 
          text-align: center; 
          margin-bottom: 30px; 
          border-bottom: 3px solid #2563eb; 
          padding-bottom: 20px; 
        }
        .header h1 { 
          color: #2563eb; 
          margin: 0 0 10px 0; 
          font-size: 2.5em; 
          font-weight: bold;
        }
        .header h2 { 
          color: #666; 
          margin: 0;
          font-size: 1.2em;
          font-weight: normal;
        }
        .bill-info { 
          display: grid; 
          grid-template-columns: 1fr 1fr; 
          gap: 30px; 
          margin-bottom: 30px; 
        }
        .info-section { 
          background: #f8fafc; 
          padding: 20px; 
          border-radius: 8px; 
          border: 1px solid #e2e8f0;
        }
        .info-section h3 { 
          margin: 0 0 15px 0; 
          color: #2563eb; 
          border-bottom: 2px solid #e2e8f0; 
          padding-bottom: 8px; 
          font-size: 1.1em;
        }
        .info-row {
          display: flex;
          justify-content: space-between;
          margin-bottom: 8px;
          padding: 4px 0;
        }
        .info-label {
          font-weight: 600;
          color: #64748b;
        }
        .info-value {
          font-weight: 500;
          color: #1e293b;
        }
        .amount-cards {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 20px;
          margin: 30px 0;
        }
        .amount-card {
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
          padding: 20px;
          border-radius: 12px;
          text-align: center;
          box-shadow: 0 4px 12px rgba(0,0,0,0.15);
        }
        .amount-card.paid {
          background: linear-gradient(135deg, #4ade80 0%, #22c55e 100%);
        }
        .amount-card.balance {
          background: linear-gradient(135deg, #f87171 0%, #ef4444 100%);
        }
        .amount-card h4 {
          margin: 0 0 8px 0;
          font-size: 0.9em;
          opacity: 0.9;
          text-transform: uppercase;
          letter-spacing: 1px;
        }
        .amount-card .amount {
          font-size: 1.8em;
          font-weight: bold;
          margin: 0;
        }
        .status-badge {
          display: inline-block;
          padding: 8px 16px;
          border-radius: 20px;
          font-weight: bold;
          font-size: 0.9em;
          text-transform: uppercase;
          letter-spacing: 1px;
        }
        .status-paid { background: #dcfce7; color: #166534; }
        .status-partial { background: #fef3c7; color: #92400e; }
        .status-unpaid { background: #fee2e2; color: #991b1b; }
        .progress-bar {
          background: #f1f5f9;
          height: 12px;
          border-radius: 6px;
          overflow: hidden;
          margin: 15px 0;
        }
        .progress-fill {
          height: 100%;
          background: linear-gradient(90deg, #22c55e 0%, #16a34a 100%);
          border-radius: 6px;
          transition: width 0.3s ease;
        }
        .footer { 
          margin-top: 40px; 
          text-align: center; 
          color: #64748b; 
          border-top: 2px solid #e2e8f0; 
          padding-top: 20px; 
          font-size: 0.9em;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin: 20px 0;
          background: white;
        }
        th, td {
          padding: 12px;
          text-align: left;
          border-bottom: 1px solid #e2e8f0;
        }
        th {
          background: #f8fafc;
          font-weight: 600;
          color: #475569;
        }
        @media print {
          body { margin: 0; }
          .container { max-width: none; }
        }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>PURCHASE BILL</h1>
          <h2>Bill Number: ${bill.CM_Bill_Number}</h2>
        </div>
        
        <div class="bill-info">
          <div class="info-section">
            <h3>Bill Information</h3>
            <div class="info-row">
              <span class="info-label">Bill ID:</span>
              <span class="info-value">${bill.CM_Purchase_Summary_ID}</span>
            </div>
            <div class="info-row">
              <span class="info-label">Bill Number:</span>
              <span class="info-value">${bill.CM_Bill_Number}</span>
            </div>
            ${bill.CM_Supplier_ID ? `
            <div class="info-row">
              <span class="info-label">Supplier ID:</span>
              <span class="info-value">${bill.CM_Supplier_ID}</span>
            </div>` : ''}
            ${bill.CM_Company_ID ? `
            <div class="info-row">
              <span class="info-label">Company ID:</span>
              <span class="info-value">${bill.CM_Company_ID}</span>
            </div>` : ''}
            ${bill.CM_Created_By ? `
            <div class="info-row">
              <span class="info-label">Created By:</span>
              <span class="info-value">${bill.CM_Created_By}</span>
            </div>` : ''}
          </div>
          
          <div class="info-section">
            <h3>Payment & Delivery</h3>
            <div class="info-row">
              <span class="info-label">Status:</span>
              <span class="info-value">
                <span class="status-badge ${bill.CM_Payment_Status === 'Paid' ? 'status-paid' :
      bill.CM_Payment_Status === 'Partially Paid' ? 'status-partial' : 'status-unpaid'
    }">${bill.CM_Payment_Status}</span>
              </span>
            </div>
            ${bill.CM_Payment_Terms ? `
            <div class="info-row">
              <span class="info-label">Payment Terms:</span>
              <span class="info-value">${bill.CM_Payment_Terms}</span>
            </div>` : ''}
            ${bill.CM_Delivery_Location ? `
            <div class="info-row">
              <span class="info-label">Delivery Location:</span>
              <span class="info-value">${bill.CM_Delivery_Location}</span>
            </div>` : ''}
            ${bill.CM_Delivery_Date ? `
            <div class="info-row">
              <span class="info-label">Delivery Date:</span>
              <span class="info-value">${new Date(bill.CM_Delivery_Date).toLocaleDateString('en-IN')}</span>
            </div>` : ''}
          </div>
        </div>

        <div class="amount-cards">
          <div class="amount-card">
            <h4>Grand Total</h4>
            <div class="amount">₹${amounts.grandTotal.toLocaleString('en-IN')}</div>
          </div>
          <div class="amount-card paid">
            <h4>Amount Paid</h4>
            <div class="amount">₹${amounts.advancePayment.toLocaleString('en-IN')}</div>
          </div>
          <div class="amount-card balance">
            <h4>Balance Due</h4>
            <div class="amount">₹${amounts.balancePayment.toLocaleString('en-IN')}</div>
          </div>
        </div>

        <div class="info-section">
          <h3>Payment Progress</h3>
          <div class="progress-bar">
            <div class="progress-fill" style="width: ${amounts.grandTotal > 0 ? Math.round((amounts.advancePayment / amounts.grandTotal) * 100) : 0}%"></div>
          </div>
          <div style="text-align: center; font-weight: 600;">
            ${amounts.grandTotal > 0 ? Math.round((amounts.advancePayment / amounts.grandTotal) * 100) : 0}% Complete
          </div>
        </div>

        <table>
          <thead>
            <tr>
              <th>Description</th>
              <th style="text-align: right;">Amount</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Tax Type</td>
              <td style="text-align: right;">${bill.CM_Tax_Type}</td>
            </tr>
            <tr>
              <td>Tax Percentage</td>
              <td style="text-align: right;">${amounts.taxPercentage.toFixed(2)}%</td>
            </tr>
            <tr>
              <td>Tax Amount</td>
              <td style="text-align: right;">₹${amounts.taxAmount.toLocaleString('en-IN', { minimumFractionDigits: 2 })}</td>
            </tr>
            <tr>
              <td>Round Off</td>
              <td style="text-align: right;">₹${amounts.roundOff.toLocaleString('en-IN', { minimumFractionDigits: 2 })}</td>
            </tr>
            <tr style="background-color: #f8fafc; font-weight: bold;">
              <td>Grand Total</td>
              <td style="text-align: right;">₹${amounts.grandTotal.toLocaleString('en-IN', { minimumFractionDigits: 2 })}</td>
            </tr>
          </tbody>
        </table>
        
        <div class="footer">
          <p><strong>Created:</strong> ${new Date(bill.CM_Created_At).toLocaleString('en-IN')}</p>
          <p><strong>Generated:</strong> ${new Date().toLocaleString('en-IN')}</p>
          <p>Purchase Management System</p>
        </div>
      </div>
    </body>
    </html>
  `;
}
